title: Godly Gamers
description: >-
  Welcome to Godly Gamers, We are a discord bot and website development company
  that is always here to help
social_link: Instagram
social_username: JoshWells
github_repo: DeveloperJosh
github_username: DeveloperJosh
theme_color: black
remote_theme: internet-de-france/swiss
baseurl: /godly_gamers
defaults:
  - scope:
      path: ''
      type: pages
    values:
      category_name: ''
  - scope:
      path: ''
      type: posts
    values:
      categories: ''
remote_theme_layouts:
  - ''
  - default
  - page
  - post
  - home
  - category_index
social_links:
  - twitter
  - instagram
  - medium
  - dribbble
theme_colors:
  - black
  - blue
  - gray
  - magenta
  - orange
  - red
  - white
  - yellow
